### PR TITLE
Package version update

### PR DESCRIPTION
**Pull request by MaryLvV**
- updated package versions in `.yaml` file
- added a few clarifications to slides and notebooks

### CODE REVIEW

**Comment by mcvholloway** [comment]
The new environment seems to be working and the notebook ran for me with no errors.

**Review by mcvholloway — APPROVED** [review]
Looks good to me.

**Comment by raom1** [comment]
Everything ran for me as well. If you're going to use the yaml, do you think the first markdown in `geospatial_intro` should be updated or removed?

**Comment by MaryLvV** [comment]
@raom1 - good catch - that's a potentially confusing message. I removed it.

**Pull request merged**
